server {
    server_name honey-moa-front;
    listen       80;
    listen  [::]:80;
 
    location / {
        root    /usr/share/nginx/html;
        proxy_pass http://15.165.181.188:3000;
        index   index.html;
        try_files $uri $uri/ /index.html;
    }
    error_page 404              /index.html;

    error_log                   /var/log/nginx/error.log;
    access_log                  /var/log/nginx/access.log;
}